
export const INIT_ROUTE = "INIT_ROUTE";

export const ONBOARDING_MAIN_ROUTE = "ONBOARDING_MAIN_ROUTE";
export const ONBOARDING_HOME_ROUTE = "ONBOARDING_HOME_ROUTE";
export const ONBOARDING_SIGNUP_ROUTE = "ONBOARDING_SIGNUP_ROUTE";

export const HOME_ROUTE = "APP_MAIN_ROUTE";

export const SETTINGS_ROUTE = "SETTINGS_ROUTE";
export const CONTACTS_ROUTE = "CONTACTS_ROUTE";
export const MESSAGES_ROUTE = "MESSAGES_ROUTE";
export const CONVERSATION_ROUTE = "CONVERSATION_ROUTE";

