
export const INIT_ROUTE = "INIT_ROUTE";

export const ONBOARDING_MAIN_ROUTE = "ONBOARDING_MAIN_ROUTE";
export const ONBOARDING_HOME_ROUTE = "ONBOARDING_HOME_ROUTE";
export const ONBOARDING_SIGNUP_ROUTE = "ONBOARDING_SIGNUP_ROUTE";

export const APP_MAIN_ROUTE = "APP_MAIN_ROUTE";
