export const AX_CONTACTS_FETCH = "AX_CONTACTS_FETCH";
export const AX_CONTACTS_FETCHING = "AX_CONTACTS_FETCHING";
export const AX_CONTACTS_FETCHED = "AX_CONTACTS_FETCHED";
export const AX_CONTACT_ADD = "AX_CONTACT_ADD";
export const AX_CONTACT_UPDATE = "AX_CONTACT_UPDATE";